import 'package:coramdeo/app/calendario/models/liturgical_day.dart';

/// Santos e memórias celebradas no Calendário Romano Geral e Próprio do Brasil.
class RomanSanctoralData {
  static final Map<String, ({String name, LiturgicalRank rank, LiturgicalColor color})> _sanctoral = {
    // JANEIRO
    '01-01': (name: 'Santa Maria, Mãe de Deus', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '01-02': (name: 'São Basílio Magno e São Gregório Nazianzeno, bispos e doutores', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-03': (name: 'Santíssimo Nome de Jesus', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-06': (name: 'Epifania do Senhor', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '01-07': (name: 'São Raimundo de Peñafort, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-13': (name: 'Santo Hilário, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-17': (name: 'Santo Antão, abade', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-20': (name: 'São Sebastião, mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '01-21': (name: 'Santa Inês, virgem e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '01-22': (name: 'São Vicente, diácono e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '01-24': (name: 'São Francisco de Sales, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-25': (name: 'Conversão de São Paulo, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '01-26': (name: 'Santos Timóteo e Tito, bispos', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-27': (name: 'Santa Ângela Mérici, virgem', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-28': (name: 'São Tomé de Aquino, presbítero e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-31': (name: 'São João Bosco, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),

    // FEVEREIRO
    '02-02': (name: 'Apresentação do Senhor', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '02-03': (name: 'São Brás, bispo e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '02-05': (name: 'Santa Águeda, virgem e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '02-06': (name: 'Santos Paulo Miki e companheiros, mártires', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '02-08': (name: 'Santa Josefina Bakhita, virgem', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-10': (name: 'Santa Escolástica, virgem', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '02-11': (name: 'Nossa Senhora de Lourdes', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-14': (name: 'Santos Cirilo e Metódio, padroeiros da Europa', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '02-17': (name: 'Sete Santos Fundadores dos Servitas', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-21': (name: 'São Pedro Damião, bispo e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-22': (name: 'Cátedra de São Pedro, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '02-23': (name: 'São Policarpo, bispo e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),

    // MARÇO
    '03-04': (name: 'São Casimiro', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-07': (name: 'Santas Perpétua e Felicidade, mártires', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '03-08': (name: 'São João de Deus, religioso', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-09': (name: 'Santa Francisca Romana, religiosa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-17': (name: 'São Patrício, bispo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-18': (name: 'São Cirilo de Jerusalém, bispo e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-19': (name: 'São José, Esposo da Bem-Aventurada Virgem Maria', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '03-23': (name: 'São Turíbio de Mogrovejo, bispo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-25': (name: 'Anunciação do Senhor', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),

    // ABRIL
    '04-02': (name: 'São Francisco de Paula, eremita', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-04': (name: 'Santo Isidoro, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-05': (name: 'São Vicente Ferrer, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-07': (name: 'São João Batista de La Salle, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '04-11': (name: 'Santo Estanislau, bispo e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '04-13': (name: 'São Martinho I, papa e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '04-21': (name: 'Santo Anselmo, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-23': (name: 'São Jorge, mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '04-24': (name: 'São Fidelis de Sigmaringa, presbítero e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '04-25': (name: 'São Marcos, evangelista', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '04-28': (name: 'São Luís Maria Grignion de Montfort, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-29': (name: 'Santa Catarina de Sena, virgem e doutora da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '04-30': (name: 'São Pio V, papa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),

    // MAIO
    '05-01': (name: 'São José Operário', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-02': (name: 'Santo Atanásio, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '05-03': (name: 'Santos Filipe e Tiago, apóstolos', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '05-12': (name: 'Santos Nereu e Aquiles, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '05-13': (name: 'Nossa Senhora de Fátima', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-14': (name: 'São Matias, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '05-18': (name: 'São João I, papa e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '05-20': (name: 'São Bernardino de Sena, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-21': (name: 'São Cristóvão Magalhães e companheiros, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '05-22': (name: 'Santa Rita de Cássia, religiosa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-25': (name: 'São Beda Venerável, presbítero e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-26': (name: 'São Filipe Néri, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '05-27': (name: 'Santo Agostinho de Cantuária, bispo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-29': (name: 'São Paulo VI, papa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-31': (name: 'Visitação da Bem-Aventurada Virgem Maria', rank: LiturgicalRank.festa, color: LiturgicalColor.white),

    // JUNHO
    '06-01': (name: 'São Justino, mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-02': (name: 'Santos Marcelino e Pedro, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '06-03': (name: 'Santos Carlos Lwanga e companheiros, mártires', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-05': (name: 'São Bonifácio, bispo e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-06': (name: 'São Norberto, bispo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-09': (name: 'Santo Efrém, diácono e doutor da Igreja', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-11': (name: 'São Barnabé, apóstolo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-13': (name: 'Santo Antônio de Lisboa e Pádua, presbítero e doutor', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '06-19': (name: 'São Romualdo, abade', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-21': (name: 'São Luís Gonzaga, religioso', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '06-22': (name: 'Santos Tomás More e João Fisher, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '06-24': (name: 'Natividade de São João Batista', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '06-27': (name: 'São Cirilo de Alexandria, bispo e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-28': (name: 'Santo Irineu, bispo, mártir e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-29': (name: 'Santos Pedro e Paulo, apóstolos', rank: LiturgicalRank.solenidade, color: LiturgicalColor.red),
    '06-30': (name: 'Primeiros Santos Mártires da Igreja de Roma', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),

    // JULHO
    '07-03': (name: 'São Tomé, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '07-04': (name: 'Santa Isabel de Portugal', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-05': (name: 'Santo Antônio Maria Zaccaria, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-06': (name: 'Santa Maria Goretti, virgem e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '07-09': (name: 'Santa Paulina do Coração Agonizante de Jesus', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-11': (name: 'São Bento, abade', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-13': (name: 'Santo Henrique', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-14': (name: 'São Camilo de Lellis, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-15': (name: 'São Boaventura, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-16': (name: 'Nossa Senhora do Carmo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-20': (name: 'Santo Apolinário, bispo e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '07-21': (name: 'São Lourenço de Brindisi, presbítero e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-22': (name: 'Santa Maria Madalena', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '07-23': (name: 'Santa Brígida, religiosa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-24': (name: 'São Charbel Makhlouf, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-25': (name: 'São Tiago, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '07-26': (name: 'Santos Joaquim e Ana, pais de Nossa Senhora', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-29': (name: 'Santos Marta, Maria e Lázaro', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-30': (name: 'São Pedro Crisólogo, bispo e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-31': (name: 'Santo Inácio de Loyola, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),

    // AGOSTO
    '08-01': (name: 'Santo Afonso Maria de Ligório, bispo e doutor', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-02': (name: 'São Pedro Julião Eymard, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-04': (name: 'São João Maria Vianney (Cura d\'Ars), presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-05': (name: 'Dedicação da Basílica de Santa Maria Maior', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-06': (name: 'Transfiguração do Senhor', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '08-07': (name: 'São Sisto II, papa, e companheiros, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '08-08': (name: 'São Domingos de Gusmão, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-09': (name: 'Santa Teresa Benedita da Cruz (Edith Stein), mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '08-10': (name: 'São Lourenço, diácono e mártir', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '08-11': (name: 'Santa Clara, virgem', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-12': (name: 'Santa Joana Francisca de Chantal, religiosa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-13': (name: 'Santos Ponciano, papa, e Hipólito, presbítero, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '08-14': (name: 'São Maximiliano Maria Kolbe, presbítero e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '08-15': (name: 'Assunção da Bem-Aventurada Virgem Maria', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '08-16': (name: 'Santo Estêvão da Hungria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-19': (name: 'São João Eudes, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-20': (name: 'São Bernardo, abade e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-21': (name: 'São Pio X, papa', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-22': (name: 'Nossa Senhora, Rainha', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-23': (name: 'Santa Rosa de Lima, virgem', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-24': (name: 'São Bartolomeu, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '08-25': (name: 'São Luís da França / São José de Calasanz', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-27': (name: 'Santa Mônica', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-28': (name: 'Santo Agostinho, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-29': (name: 'Martírio de São João Batista', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),

    // SETEMBRO
    '09-03': (name: 'São Gregório Magno, papa e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-08': (name: 'Natividade de Nossa Senhora', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '09-09': (name: 'São Pedro Claver, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '09-12': (name: 'Santíssimo Nome de Maria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '09-13': (name: 'São João Crisóstomo, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-14': (name: 'Exaltação da Santa Cruz', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '09-15': (name: 'Nossa Senhora das Dores', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-16': (name: 'Santos Cornélio, papa, e Cipriano, bispo, mártires', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '09-17': (name: 'São Roberto Belarmino, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '09-19': (name: 'São Januário, bispo e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '09-20': (name: 'Santos André Kim Taegon e companheiros, mártires', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '09-21': (name: 'São Mateus, apóstolo e evangelista', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '09-23': (name: 'São Pio de Pietrelcina (Padre Pio), presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-26': (name: 'Santos Cosme e Damião, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '09-27': (name: 'São Vicente de Paulo, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-28': (name: 'São Venceslau, mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '09-29': (name: 'Santos Miguel, Gabriel e Rafael, Arcanjos', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '09-30': (name: 'São Jerônimo, presbítero e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),

    // OUTUBRO
    '10-01': (name: 'Santa Teresinha do Menino Jesus, virgem e doutora', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-02': (name: 'Santos Anjos da Guarda', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-04': (name: 'São Francisco de Assis', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-05': (name: 'Santa Faustina Kowalska, virgem', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-06': (name: 'São Bruno, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-07': (name: 'Nossa Senhora do Rosário', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-09': (name: 'São Dionísio, bispo, e companheiros, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '10-11': (name: 'São João XXIII, papa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-12': (name: 'Nossa Senhora da Conceição Aparecida, Padroeira do Brasil', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '10-14': (name: 'São Calisto I, papa e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '10-15': (name: 'Santa Teresa de Jesus (de Ávila), virgem e doutora', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-16': (name: 'Santa Edwiges, religiosa / Santa Margarida Maria Alacoque', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-17': (name: 'Santo Inácio de Antioquia, bispo e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '10-18': (name: 'São Lucas, evangelista', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '10-19': (name: 'Santos João de Brébeuf, Isaac Jogues e companheiros, mártires', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '10-22': (name: 'São João Paulo II, papa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-23': (name: 'São João de Capistrano, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-24': (name: 'Santo Antônio Maria Claret, bispo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-28': (name: 'Santos Simão e Judas, apóstolos', rank: LiturgicalRank.festa, color: LiturgicalColor.red),

    // NOVEMBRO
    '11-01': (name: 'Todos os Santos', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '11-02': (name: 'Comemoração de Todos os Fiéis Defuntos', rank: LiturgicalRank.solenidade, color: LiturgicalColor.purple),
    '11-03': (name: 'São Martinho de Lima, religioso', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-04': (name: 'São Carlos Borromeu, bispo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-09': (name: 'Dedicação da Basílica de Latrão', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '11-10': (name: 'São Leão Magno, papa e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-11': (name: 'São Martinho de Tours, bispo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-12': (name: 'São Josafá, bispo e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '11-15': (name: 'Santo Alberto Magno, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-16': (name: 'Santa Margarida da Escócia / Santa Gertrudes, virgem', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-17': (name: 'Santa Isabel da Hungria, religiosa', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-18': (name: 'Dedicação das Basílicas de São Pedro e São Paulo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-21': (name: 'Apresentação da Bem-Aventurada Virgem Maria', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-22': (name: 'Santa Cecília, virgem e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '11-23': (name: 'São Clemente I, papa e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '11-24': (name: 'Santo André Dung-Lac e companheiros, mártires', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '11-25': (name: 'Santa Catarina de Alexandria, virgem e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '11-30': (name: 'Santo André, apóstolo', rank: LiturgicalRank.festa, color: LiturgicalColor.red),

    // DEZEMBRO
    '12-03': (name: 'São Francisco Xavier, presbítero', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '12-04': (name: 'São João Damasceno, presbítero e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-06': (name: 'São Nicolau, bispo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-07': (name: 'Santo Ambrósio, bispo e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '12-08': (name: 'Imaculada Conceição da Bem-Aventurada Virgem Maria', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '12-09': (name: 'São Juan Diego Cuauhtlatoatzin', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-10': (name: 'Nossa Senhora de Loreto', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-11': (name: 'São Dâmaso I, papa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-12': (name: 'Nossa Senhora de Guadalupe, Padroeira da América Latina', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '12-13': (name: 'Santa Luzia, virgem e mártir', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '12-14': (name: 'São João da Cruz, presbítero e doutor da Igreja', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '12-21': (name: 'São Pedro Canísio, presbítero e doutor', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-23': (name: 'São João de Kenty, presbítero', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-25': (name: 'Natal de Nosso Senhor Jesus Cristo', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '12-26': (name: 'Santo Estêvão, primeiro mártir', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '12-27': (name: 'São João, apóstolo e evangelista', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '12-28': (name: 'Santos Inocentes, mártires', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '12-29': (name: 'São Tomás Becket, bispo e mártir', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '12-31': (name: 'São Silvestre I, papa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
  };

  /// Obtém a comemoração de santo ou memória para determinado mês e dia.
  static ({String name, LiturgicalRank rank, LiturgicalColor color})? getSaint(int month, int day) {
    final key = '${month.toString().padLeft(2, '0')}-${day.toString().padLeft(2, '0')}';
    return _sanctoral[key];
  }
}

