import 'package:coramdeo/app/calendario/models/liturgical_day.dart';

/// Santos e memórias celebradas no Calendário Romano Geral e Próprio do Brasil.
class RomanSanctoralData {
  static final Map<String, ({String name, LiturgicalRank rank, LiturgicalColor color})> _sanctoral = {
    // JANEIRO
    '01-01': (name: 'Santa Maria, Mãe de Deus', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '01-02': (name: 'São Basílio Magno e São Gregório Nazianzeno', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-03': (name: 'Santíssimo Nome de Jesus', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-06': (name: 'Epifania do Senhor', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '01-07': (name: 'São Raimundo de Peñafort', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-13': (name: 'Santo Hilário', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-17': (name: 'Santo Antão', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-20': (name: 'São Sebastião', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '01-21': (name: 'Santa Inês', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '01-22': (name: 'São Vicente', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '01-24': (name: 'São Francisco de Sales', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-25': (name: 'Conversão de São Paulo', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '01-26': (name: 'Santos Timóteo e Tito', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-27': (name: 'Santa Ângela Mérici', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '01-28': (name: 'São Tomás de Aquino', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '01-31': (name: 'São João Bosco', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),

    // FEVEREIRO
    '02-02': (name: 'Apresentação do Senhor', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '02-03': (name: 'São Brás', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '02-05': (name: 'Santa Águeda', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '02-06': (name: 'Santos Paulo Miki e Companheiros', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '02-08': (name: 'Santa Josefina Bakhita', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-10': (name: 'Santa Escolástica', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '02-11': (name: 'Nossa Senhora de Lourdes', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-14': (name: 'Santos Cirilo e Metódio', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '02-17': (name: 'Sete Santos Fundadores dos Servitas', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-21': (name: 'São Pedro Damião', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '02-22': (name: 'Cátedra de São Pedro', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '02-23': (name: 'São Policarpo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),

    // MARÇO
    '03-04': (name: 'São Casimiro', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-07': (name: 'Santas Perpétua e Felicidade', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '03-08': (name: 'São João de Deus', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-09': (name: 'Santa Francisca Romana', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-17': (name: 'São Patrício', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-18': (name: 'São Cirilo de Jerusalém', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-19': (name: 'São José', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '03-23': (name: 'São Turíbio de Mogrovejo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '03-25': (name: 'Anunciação do Senhor', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),

    // ABRIL
    '04-02': (name: 'São Francisco de Paula', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-04': (name: 'Santo Isidoro', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-05': (name: 'São Vicente Ferrer', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-07': (name: 'São João Batista de La Salle', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '04-11': (name: 'Santo Estanislau', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '04-13': (name: 'São Martinho I', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '04-21': (name: 'Santo Anselmo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-23': (name: 'São Jorge', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '04-24': (name: 'São Fidélis de Sigmaringa', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '04-25': (name: 'São Marcos', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '04-28': (name: 'São Luís Maria Grignion de Montfort', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '04-29': (name: 'Santa Catarina de Sena', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '04-30': (name: 'São Pio V', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),

    // MAIO
    '05-01': (name: 'São José Operário', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-02': (name: 'Santo Atanásio', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '05-03': (name: 'Santos Filipe e Tiago', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '05-12': (name: 'Santos Nereu e Aquiles', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '05-13': (name: 'Nossa Senhora de Fátima', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-14': (name: 'São Matias', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '05-18': (name: 'São João I', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '05-20': (name: 'São Bernardino de Sena', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-21': (name: 'São Cristóvão Magalhães e Companheiros', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '05-22': (name: 'Santa Rita de Cássia', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-25': (name: 'São Beda Venerável', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-26': (name: 'São Filipe Néri', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '05-27': (name: 'Santo Agostinho de Cantuária', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-29': (name: 'São Paulo VI', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '05-31': (name: 'Visitação de Nossa Senhora', rank: LiturgicalRank.festa, color: LiturgicalColor.white),

    // JUNHO
    '06-01': (name: 'São Justino', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-02': (name: 'Santos Marcelino e Pedro', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '06-03': (name: 'Santos Carlos Lwanga e Companheiros', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-05': (name: 'São Bonifácio', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-06': (name: 'São Norberto', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-09': (name: 'Santo Efrém', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-11': (name: 'São Barnabé', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-13': (name: 'Santo Antônio de Pádua', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '06-19': (name: 'São Romualdo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-21': (name: 'São Luís Gonzaga', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '06-22': (name: 'Santos Tomás More e João Fisher', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '06-24': (name: 'Natividade de São João Batista', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '06-27': (name: 'São Cirilo de Alexandria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '06-28': (name: 'Santo Irineu', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '06-29': (name: 'Santos Pedro e Paulo', rank: LiturgicalRank.solenidade, color: LiturgicalColor.red),
    '06-30': (name: 'Primeiros Santos Mártires de Roma', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),

    // JULHO
    '07-03': (name: 'São Tomé', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '07-04': (name: 'Santa Isabel de Portugal', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-05': (name: 'Santo Antônio Maria Zaccaria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-06': (name: 'Santa Maria Goretti', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '07-09': (name: 'Santa Paulina', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-11': (name: 'São Bento', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-13': (name: 'Santo Henrique', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-14': (name: 'São Camilo de Léllis', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-15': (name: 'São Boaventura', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-16': (name: 'Nossa Senhora do Carmo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-20': (name: 'Santo Apolinário', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '07-21': (name: 'São Lourenço de Brindisi', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-22': (name: 'Santa Maria Madalena', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '07-23': (name: 'Santa Brígida', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-24': (name: 'São Charbel Makhlouf', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-25': (name: 'São Tiago Maior', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '07-26': (name: 'Santos Joaquim e Ana', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-29': (name: 'Santos Marta, Maria e Lázaro', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '07-30': (name: 'São Pedro Crisólogo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '07-31': (name: 'Santo Inácio de Loyola', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),

    // AGOSTO
    '08-01': (name: 'Santo Afonso Maria de Ligório', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-02': (name: 'São Pedro Julião Eymard', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-04': (name: 'São João Maria Vianney', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-05': (name: 'Dedicação de Santa Maria Maior', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-06': (name: 'Transfiguração do Senhor', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '08-07': (name: 'São Sisto II e Companheiros', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '08-08': (name: 'São Domingos de Gusmão', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-09': (name: 'Santa Teresa Benedita da Cruz', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '08-10': (name: 'São Lourenço', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '08-11': (name: 'Santa Clara', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-12': (name: 'Santa Joana Francisca de Chantal', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-13': (name: 'Santos Ponciano e Hipólito', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '08-14': (name: 'São Maximiliano Maria Kolbe', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '08-15': (name: 'Assunção de Nossa Senhora', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '08-16': (name: 'Santo Estêvão da Hungria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-19': (name: 'São João Eudes', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-20': (name: 'São Bernardo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-21': (name: 'São Pio X', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-22': (name: 'Nossa Senhora Rainha', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-23': (name: 'Santa Rosa de Lima', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-24': (name: 'São Bartolomeu', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '08-25': (name: 'São Luís da França', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '08-27': (name: 'Santa Mônica', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-28': (name: 'Santo Agostinho', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '08-29': (name: 'Martírio de São João Batista', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),

    // SETEMBRO
    '09-03': (name: 'São Gregório Magno', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-08': (name: 'Natividade de Nossa Senhora', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '09-09': (name: 'São Pedro Claver', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '09-12': (name: 'Santíssimo Nome de Maria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '09-13': (name: 'São João Crisóstomo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-14': (name: 'Exaltação da Santa Cruz', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '09-15': (name: 'Nossa Senhora das Dores', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-16': (name: 'Santos Cornélio e Cipriano', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '09-17': (name: 'São Roberto Belarmino', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '09-19': (name: 'São Januário', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '09-20': (name: 'Santos André Kim Taegon e Companheiros', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '09-21': (name: 'São Mateus', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '09-23': (name: 'São Pio de Pietrelcina (Padre Pio)', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-26': (name: 'Santos Cosme e Damião', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '09-27': (name: 'São Vicente de Paulo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '09-28': (name: 'São Venceslau', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '09-29': (name: 'Santos Arcanjos Miguel, Gabriel e Rafael', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '09-30': (name: 'São Jerônimo', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),

    // OUTUBRO
    '10-01': (name: 'Santa Teresinha do Menino Jesus', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-02': (name: 'Santos Anjos da Guarda', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-04': (name: 'São Francisco de Assis', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-05': (name: 'Santa Faustina Kowalska', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-06': (name: 'São Bruno', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-07': (name: 'Nossa Senhora do Rosário', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-09': (name: 'São Dionísio e Companheiros', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '10-11': (name: 'São João XXIII', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-12': (name: 'Nossa Senhora da Conceição Aparecida', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '10-14': (name: 'São Calisto I', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '10-15': (name: 'Santa Teresa de Ávila', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '10-16': (name: 'Santa Edwiges', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-17': (name: 'Santo Inácio de Antioquia', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '10-18': (name: 'São Lucas', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '10-19': (name: 'Santos João de Brébeuf, Isaac Jogues e Companheiros', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '10-22': (name: 'São João Paulo II', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-23': (name: 'São João de Capistrano', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-24': (name: 'Santo Antônio Maria Claret', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '10-28': (name: 'Santos Simão e Judas', rank: LiturgicalRank.festa, color: LiturgicalColor.red),

    // NOVEMBRO
    '11-01': (name: 'Todos os Santos', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '11-02': (name: 'Comemoração de Todos os Fiéis Defuntos', rank: LiturgicalRank.solenidade, color: LiturgicalColor.purple),
    '11-03': (name: 'São Martinho de Lima', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-04': (name: 'São Carlos Borromeu', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-09': (name: 'Dedicação da Basílica de Latrão', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '11-10': (name: 'São Leão Magno', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-11': (name: 'São Martinho de Tours', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-12': (name: 'São Josafá', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '11-15': (name: 'Santo Alberto Magno', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-16': (name: 'Santa Margarida da Escócia', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-17': (name: 'Santa Isabel da Hungria', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-18': (name: 'Dedicação das Basílicas de São Pedro e São Paulo', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '11-21': (name: 'Apresentação de Nossa Senhora', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '11-22': (name: 'Santa Cecília', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '11-23': (name: 'São Clemente I', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '11-24': (name: 'Santo André Dung-Lac e Companheiros', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '11-25': (name: 'Santa Catarina de Alexandria', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '11-30': (name: 'Santo André', rank: LiturgicalRank.festa, color: LiturgicalColor.red),

    // DEZEMBRO
    '12-03': (name: 'São Francisco Xavier', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '12-04': (name: 'São João Damasceno', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-06': (name: 'São Nicolau', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-07': (name: 'Santo Ambrósio', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '12-08': (name: 'Imaculada Conceição de Nossa Senhora', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '12-09': (name: 'São Juan Diego', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-10': (name: 'Nossa Senhora de Loreto', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-11': (name: 'São Dâmaso I', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-12': (name: 'Nossa Senhora de Guadalupe', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '12-13': (name: 'Santa Luzia', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.red),
    '12-14': (name: 'São João da Cruz', rank: LiturgicalRank.memoriaObrigatoria, color: LiturgicalColor.white),
    '12-21': (name: 'São Pedro Canísio', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-23': (name: 'São João de Kenty', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
    '12-25': (name: 'Natal de Nosso Senhor Jesus Cristo', rank: LiturgicalRank.solenidade, color: LiturgicalColor.white),
    '12-26': (name: 'Santo Estêvão', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '12-27': (name: 'São João Evangelista', rank: LiturgicalRank.festa, color: LiturgicalColor.white),
    '12-28': (name: 'Santos Inocentes', rank: LiturgicalRank.festa, color: LiturgicalColor.red),
    '12-29': (name: 'São Tomás Becket', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.red),
    '12-31': (name: 'São Silvestre I', rank: LiturgicalRank.memoriaFacultativa, color: LiturgicalColor.white),
  };

  /// Obtém a comemoração de santo ou memória para determinado mês e dia.
  static ({String name, LiturgicalRank rank, LiturgicalColor color})? getSaint(int month, int day) {
    final key = '${month.toString().padLeft(2, '0')}-${day.toString().padLeft(2, '0')}';
    return _sanctoral[key];
  }
}
