name: Android Release

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
      - uses: actions/checkout@v4
      - name: Setup Java to compile Android project
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          cache: 'gradle'
      - name: Install and set Flutter version
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test
      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1   
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/apk/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_PASSWORD_ALIAS }}         
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}             
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      - run: |
          flutter build apk --split-per-abi
          --obfuscate
          --split-debug-info "./.debug_info" 
          --build-name "0.${{ github.run_number }}" 
          --build-number ${{ github.run_number }} 
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-arm64-v8a-release.apk,build/app/outputs/apk/release/app-armeabi-v7a-release.apk,build/app/outputs/apk/release/app-x86_64-release.apk"
          tag: v0.${{ github.run_number }}
